### ISSUE TITLE
can't find include file

### ISSUE THREAD

**Issue by skorotkiewicz** [abhinavsingh/mod_message_carbon#7]
root@aaa:~/mod_message_carbon# ./build.sh 
Recompile: src/mod_message_carbon
src/mod_message_carbon.erl:12: can't find include file "ejabberd.hrl"
src/mod_message_carbon.erl:13: can't find include file "jlib.hrl"
src/mod_message_carbon.erl:61: record iq undefined
src/mod_message_carbon.erl:62: record jid undefined
src/mod_message_carbon.erl:62: record jid undefined
src/mod_message_carbon.erl:62: record jid undefined
src/mod_message_carbon.erl:63: record iq undefined
src/mod_message_carbon.erl:64: record iq undefined
src/mod_message_carbon.erl:65: record jid undefined
src/mod_message_carbon.erl:65: record jid undefined
src/mod_message_carbon.erl:65: record jid undefined
src/mod_message_carbon.erl:66: record iq undefined
src/mod_message_carbon.erl:74: record jid undefined
src/mod_message_carbon.erl:92: record jid undefined
src/mod_message_carbon.erl:93: record jid undefined
src/mod_message_carbon.erl:95: record jid undefined
src/mod_message_carbon.erl:96: record jid undefined
src/mod_message_carbon.erl:96: record jid undefined
src/mod_message_carbon.erl:107: record jid undefined
src/mod_message_carbon.erl:107: record jid undefined
src/mod_message_carbon.erl:10: Warning: behaviour gen_mod undefined

**Comment by abhinavsingh** [comment]
@modInfo check https://github.com/abhinavsingh/mod_message_carbon/blob/master/Emakefile, you may have to update hardcoded include/lib paths

**Comment by skorotkiewicz** [comment]
thanks
